# Generated by Django 5.0.7 on 2024-07-17 11:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('bl', 'Black'), ('gr', 'Green'), ('wh', 'White'), ('oo', 'Oolong'), ('ro', 'Rooibos')], max_length=2)),
            ],
        ),
    ]
